added option to only copy a file without templating
StephanHCB/go-generator-lib pull request #19
Opened 2022-06-20 12:58 UTC by mplushnikov

2022-06-20 17:40 UTC, StephanHCB requested changes

2022-06-20 18:21 UTC, StephanHCB commented
Oh, I just noticed your commit message. Please use semver style commit messages, in this case feat(<issue>): description, so the new feature shows up in the changes log and semantic bot assigns a new version when merged. Thank you!

2022-06-21 13:23 UTC, mplushnikov commented on internal/implementation/implementation.go
> +	if tplSpec.JustCopy {
Updated pr, added test and refactored function names.
Didn't change anything for withItems now. Unfortunatly it requires deep refactoring of current implementation to be done without a lot of duplicated code.

2022-06-21 14:58 UTC, mplushnikov commented on internal/implementation/implementation.go
> +	if tplSpec.JustCopy {
Now-> new version with wrapper based implementation

2022-06-22 13:35 UTC, StephanHCB approved these changes

2022-06-22 14:10 UTC, merged